create database [QL_CHTienLoi]
go
use [QL_CHTienLoi]
go
--bảng nhân viên
CREATE TABLE NHANVIEN
(
	MANV		INT PRIMARY KEY IDENTITY(1, 1), --Mã nhân viên tự tăng
	HOTEN		NVARCHAR(50),
	NGAYSINH	DATE, --Ngày sinh
	NGAYVL		DATE, --Ngày vào làm
	TENDN		CHAR(50), --tên đăng nhập
	SDT			CHAR(11),
	DIACHI		NVARCHAR(MAX)
)
--bảng loại sản phẩm
CREATE TABLE LOAISP
(
	MALOAI	INT PRIMARY KEY IDENTITY(1, 1),
	TENLOAI	NVARCHAR(50)
)
--bảng kho
CREATE TABLE PHIEUNHAP
(
	MASP	INT PRIMARY KEY IDENTITY(1,1),
	NGAYNHAP	DATE,
	SLTON	INT CHECK (SLTON >= 0),
	MANV	INT,
	GIANHAP	FLOAT CHECK (GIANHAP >= 0),
	DVT NVARCHAR(20),
	CONSTRAINT FK_PHIEUNHAP_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
--bảng sản phẩm
CREATE TABLE SANPHAM
(
	MASP	INT PRIMARY KEY,
	TENSP	NVARCHAR(100),
	MALOAI	INT,
	NGAYSX	DATE,
	NGAYHH	DATE, --Ngày hết hạn
	DONGIA	FLOAT CHECK (DONGIA > 0),
	CONSTRAINT FK_SANPHAM_MALOAI FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI),
	FOREIGN KEY (MASP) REFERENCES PHIEUNHAP(MASP)
)

--Bảng khách hàng
CREATE TABLE KHACHHANG
(
	MAKH	INT PRIMARY KEY IDENTITY(1, 1),
	HOTEN	NVARCHAR(50),
	SDT		CHAR(11),
	DIACHI	NVARCHAR(MAX)
)
--bảng tích điểm

--Bảng hóa đơn
CREATE TABLE HOADON
(
	MAHD	INT PRIMARY KEY IDENTITY(1, 1),
	MAKH	INT,
	MANV	INT,
	NGAYLAP	DATE DEFAULT GETDATE(),
	TRANGTHAI NVARCHAR(30) CHECK(TRANGTHAI = N'Đã xuất hóa đơn' or TRANGTHAI = N'Chưa xuất') default N'Chưa xuất',
	TIENKD	FLOAT, --Tiền khách đưa
	CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

--Bảng chi tiết hóa đơn
CREATE TABLE CT_HOADON
(
	MAHD	INT,
	MASP	INT,
	SOLUONG	INT,
	THANHTIEN	FLOAT,
	CONSTRAINT PK_CT_HOADON PRIMARY KEY (MAHD, MASP),
	CONSTRAINT FK_CT_HOADON_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CT_HOADON_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
)
--TRIGGER
--Summary: TRIGGER Này dùng để ràng buộc ngày sản xuất phải nhỏ hơn hạn sử dụng.
CREATE TRIGGER NgaySX 
ON SANPHAM
AFTER INSERT, UPDATE
AS
BEGIN
	SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted
        WHERE NgaySX > NgayHH
    )
    BEGIN
        PRINT 'THÊM THẤT BẠI';
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        PRINT 'THÊM THÀNH CÔNG'; 
    END
END
SET DATEFORMAT DMY
INSERT INTO SANPHAM(NGAYSX, NGAYHH) VALUES ('20-10-2025', '20-10-2024')
update SANPHAM set NGAYSX = '20-10-2025' where MASP = 7

GO
--PROCEDURE STORE
--Xuất sản phẩm ra
CREATE PROC Select_CTHoaDon @MAHD int
AS
BEGIN 
	SELECT ct.MASP AS N'Mã sản phẩm', 
	   sp.TENSP AS N'Tên sản phẩm', 
	   sp.DONGIA AS N'Đơn giá', 
	   ct.SOLUONG as N'Số lượng', 
	   ct.SOLUONG * sp.DONGIA as N'Thành tiền'
	FROM CT_HOADON ct, SANPHAM sp
	WHERE ct.MASP = sp.MASP AND MAHD = @MAHD
END
exec Select_CTHoaDon 6
GO
--Tính tổng thành tiền
CREATE PROC Tong_ThanhTien @MAHD int
AS
BEGIN
	SELECT ct.MAHD, sum(SOLUONG * DONGIA) as 'Thành tiền'
	FROM CT_HOADON ct, SANPHAM sp
	WHERE ct.MASP = sp.MASP AND MAHD = @MAHD
	GROUP BY ct.MAHD
END

exec Tong_ThanhTien 23
GO
--Xuất hóa đơn (Mới)
ALTER PROC sp_XuatHoaDon @MAHD int
AS
BEGIN
	SELECT	ct.MAHD, 
			nv.HOTEN,
			hd.NGAYLAP,
			sp.TENSP, 
			ct.SOLUONG, 
			sp.DONGIA, 
			ct.SOLUONG * sp.DONGIA AS N'Thành Tiền',
			hd.TIENKD
	FROM CT_HOADON ct, HOADON hd, NHANVIEN nv, SANPHAM sp
	where ct.MAHD = hd.MAHD AND hd.MANV = nv.MANV AND sp.MASP = ct.MASP AND ct.MAHD = @MAHD
END
--FUNCTION
--QUERY

--DROP TABLE  HOADON
--DROP TABLE CT_HOADON
--DROP TABLE KHACHHANG
--DROP TABLE NHANVIEN
--DROP TABLE LOAISP
--drop TABLE SANPHAM
--DROP FK_SANPHAM_MALOAI

--SECURITY 
CREATE TABLE MANHINH
(
	ID	INT PRIMARY KEY IDENTITY(1, 1),
	TENMH	NVARCHAR(100),
	USERROLE	NVARCHAR(30)
)
--Authentication and Authorize
CREATE ROLE _ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE TO _ADMIN
GO
CREATE ROLE _NVTHUNGAN
GO
CREATE ROLE _NVKIEMKE
GO

--CREATE LOGIN AdminQL WITH PASSWORD = '123'
--CREATE USER AdminQL FOR LOGIN[AdminQL]

SELECT NGAYNHAP
FROM PHIEUNHAP n, SANPHAM s
WHERE n.MASP = s.MASP
GROUP BY NGAYNHAP
SET IDENTITY_INSERT [dbo].[PHIEUNHAP] ON 
INSERT INTO PHIEUNHAP VALUES (4, '2024-07-18', 42, 1, 30000, 'Lốc');
INSERT INTO PHIEUNHAP VALUES (5, '2024-07-18', 23, 1, 15000, 'Chiếc');
INSERT INTO PHIEUNHAP VALUES (6, '2024-07-18', 100, 1, 240000, 'Bao');
INSERT INTO PHIEUNHAP VALUES (7, '2024-07-20', 150, 1, 13000, 'Dây');
INSERT INTO PHIEUNHAP VALUES (8, '2024-07-22', 200, 1, 4000, 'Gói');
INSERT INTO PHIEUNHAP VALUES (9, '2024-07-19', 300, 1, 15000, 'Túi');
INSERT INTO PHIEUNHAP VALUES (10, '2024-07-19', 80, 1, 200000, 'Con');
INSERT INTO PHIEUNHAP VALUES (11, '2024-07-17', 213, 1, 9000, 'Bịch');
INSERT INTO PHIEUNHAP VALUES (12, '2024-07-16', 125, 1, 15000, 'Cái');
INSERT INTO PHIEUNHAP VALUES (13, '2024-07-23', 21, 1, 50000, 'Lốc');
INSERT INTO PHIEUNHAP VALUES (14, '2024-06-12', 41, 1, 18000, 'Chai');
INSERT INTO PHIEUNHAP VALUES (15, '2024-06-21', 51, 1, 22000, 'Cây');
INSERT INTO PHIEUNHAP VALUES (16, '2024-07-13', 145, 1, 7000, 'Bao');
INSERT INTO PHIEUNHAP VALUES (17, '2024-07-14', 20, 1, 170000, 'Con');
INSERT INTO PHIEUNHAP VALUES (18, '2024-07-23', 32, 1, 6000, 'Hộp');
INSERT INTO PHIEUNHAP VALUES (19, '2024-06-29', 45, 1, 39000, 'Hộp');
INSERT INTO PHIEUNHAP VALUES (20, '2024-04-12', 50, 1, 20000, 'Cái');

INSERT INTO PHIEUNHAP VALUES (4, '2024-07-18', 42, 1, 30000, 'Lốc')
SELECT * FROM HOADON
select * from SANPHAM
exec Select_CTHoaDon 
EXEC Tong_ThanhTien 57

SELECT NGAYNHAP FROM PHIEUNHAP GROUP BY NGAYNHAP