//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_CHTienLoiEntities : DbContext
    {
        public QL_CHTienLoiEntities()
            : base("name=QL_CHTienLoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOADON> CT_HOADON { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual ObjectResult<Select_CTHoaDon_Result> Select_CTHoaDon(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_CTHoaDon_Result>("Select_CTHoaDon", mAHDParameter);
        }
    
        public virtual ObjectResult<string> sp_LoginUser(string uSERNAME, string pASSWORD)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LoginUser", uSERNAMEParameter, pASSWORDParameter);
        }
    
        public virtual ObjectResult<Tong_ThanhTien_Result> Tong_ThanhTien(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tong_ThanhTien_Result>("Tong_ThanhTien", mAHDParameter);
        }
    }
}
