//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOADON> CT_HOADON { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TICHDIEM> TICHDIEMs { get; set; }
    
        public virtual ObjectResult<Select_CTHoaDon_Result> Select_CTHoaDon(string mAHD)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_CTHoaDon_Result>("Select_CTHoaDon", mAHDParameter);
        }
    
        public virtual ObjectResult<sp_XuatHoaDon_Result> sp_XuatHoaDon(string mAHD)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XuatHoaDon_Result>("sp_XuatHoaDon", mAHDParameter);
        }
    
        public virtual ObjectResult<Tong_ThanhTien_Result> Tong_ThanhTien(string mAHD)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tong_ThanhTien_Result>("Tong_ThanhTien", mAHDParameter);
        }
    }
}
