//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public string MAKM { get; set; }
        public string TENKM { get; set; }
        public string MASP { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYHH { get; set; }
        public Nullable<int> SLMUA { get; set; }
        public string SPTANG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
