//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICHDIEM
    {
        public string MAKH { get; set; }
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYTICH { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
